# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-31 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NeighborHood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=100)),
                ('occupant_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
